### ISSUE TITLE
[Editor] Userdoc service incorrectly handles nested types

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#1102]
**Release Type**: GitHub

**Version**: master

**Platform(s)**: N/A

**Describe the bug**
`UserDocumentationService` has no logic regarding nested types. When you call `Type.FullName` on a nested class it appears as `Namespace.ParentClass+NestedClass`. The `userdoc` file does not use `+` and just has a `.` (dot) in there instead. In the service when getting a description for a type there should be a substitution of `+` with `.`, otherwise nested classes will not have documentation on their properties.

**Comment by AmbulantRex** [comment]
@manio143 The PropertyDescriptor used in the process takes a TypeDescriptorFactory whose default naming convention is for YAML. From my initial investigation, I see 2 potential solutions:
1) Use a different factory when constructing these property descriptors that considers a `.` instead of a `+` for subclasses
2) Replace the `+` with a `.` in the UserDocumentationService through a pattern match. 

I'll look into this more later. I'd like to avoid the second option because it's hacky...

**Comment by AmbulantRex** [comment]
I retracted my previous assessment. Looking closer, C# is responsible for adding the `+` when generating the MemberInfo which we use for determining the key. However, the XML output does _not_ use the `+` and instead uses the `.` to denote subclasses. This difference means that, while hacky, a simple replacement of the `+` in the key name when trying to retrieve from cache is likely all that can be done:

![image](https://user-images.githubusercontent.com/21176662/129382732-6add5640-f576-4fa6-889e-49280c02dbd3.png)
