### ISSUE TITLE
Stride.sln - Build errors

### ISSUE THREAD

**Issue by MappingSteve** [stride3d/stride#1179]
**Release Type**: GitHub

**Version**: master

**Platform(s)**: Windows 10

**Describe the bug**
"Rebuild Solution" => Build errors.

**To Reproduce**
1. Download master branch.
2. Open stride.sln in VS2019
3. "Win32" Config.
4. Rt-click Stride.GameStudio / Build Project.

**Expected behavior**
Build without errors.

**Log and callstacks**
See next comment - maybe this machine didn't have all prerequisites.

**Additional context**
* First time attempting to build stride source.

**Comment by ToolmakerSteve** [comment]
Is there a documented list of prerequisites? That output was on a pc that doesn't have as much installed. Here's build output from my main pc:

[Stride Output-Build.txt](https://github.com/stride3d/stride/files/7489444/Stride.Output-Build.txt)

**Comment by ToolmakerSteve** [comment]
Works now.

I had three problems:

1. First, was selecting "Win32" config. Out of habit.
2. NOT realizing I needed "Mixed Platforms" config - I tried to fix (1) by going to "Any CPU". Then I looked at what was actually included in each config. I had mis-learned to avoid "Mixed Platforms", due to an unrelated solution I use a lot, in which that is messed up. (If I had deleted my .suo, to restore to original settings, I would have discovered it was originally "Mixed Platforms".)
3. Was missing FBX SDK 2019.

I think (3) needs to be added to build instructions.

**Comment by xen2** [comment]
List of prereq is on the main README.md: https://github.com/stride3d/stride#prerequisites

**Comment by ToolmakerSteve** [comment]
Yeah. I have no idea why "(3) FBX SDK" was mentally invisible to me. I carefully went through all the (2) VS requirements. While waiting for those to install, read "Build Stride" after that.

Never saw the FBX line.

**Comment by ToolmakerSteve** [comment]
FWIW, if anyone else overlooks that, then maybe move the one line FBX requirement to BEFORE the lengthy VS requirement. So it doesn’t get overlooked.
