### ISSUE TITLE
How the engine is developing now

### ISSUE THREAD

**Issue by howarduong** [stride3d/stride#1519]
# Question and/or Comment
Is there a complete mmorpg example? Similar to wow.
I am very optimistic about this engine. I have been following it for a few years since the establishment of the xenko project. It has now been renamed stride. It seems that the development of new features is very slow, and the asset store has not been capped.
It seems that the question about the terrain landscape was mentioned a long time ago, and it seems that it has not been updated yet.
There used to be a project development target schedule, but now I can't find it.
There used to be a Chinese language pack and now there is no more.

**Comment by howarduong** [comment]
Assuming that stride has a relatively complete community store,
Some assets that can complete the game, similar to ue's core, will more people participate in it? Those with programming ability can participate in advanced programming, those without programming skills can make mod changes to the game, cover the largest number of users, and fully display their creativity. There are many successful examples of this. For example, the editor of war3 created an era, creating Dota, and The Elder Scrolls, etc.
I hope that we can be close to the user to advance the work, not to work behind closed doors.

**Comment by ykafia** [comment]
I agree with you, it would be nice to have more people working with and on the engine.

There is currently no direction given nor followed by contributors since everyone is working on their time off mostly. That usually means they are working on the low hanging issues of the engine first, the biggest endeavors (editor/marketplace/big updates) are very intricate and really need teams to work on them.

**Comment by howarduong** [comment]
You can consider launching the engine to the steam platform first

**Comment by Eideren** [comment]
I guess this has been answered ?
