### ISSUE TITLE
How to create a project without an editor?

### ISSUE THREAD

**Issue by VeyDlin** [stride3d/stride#1581]
I'm making a 3d viewer and I want to use stride in avalonia

My question is, how can I create a stride project using only code? Specifically, I am interested in the following things:

1) I want to let users make materials using nodes (as in blender), how can I create and compile shaders and materials directly from the code?

2) How to create a scene and add everything minimally necessary from the code to it?

3) To make a window in avalonia, I need to subscribe to the frame rendering event and get context at every update, how can I do that?

4) Ideally, it would be possible to allow avalonia to manage rendering, i.e. is it possible to manually call rendering of each frame from the outside?

**Comment by manio143** [comment]
When it comes to Stride, code only approach is very much possible. You can take a look at https://github.com/VaclavElias/stride-code-only for a general ideas.

For the integration with Avalonia, I believe there may have been attempts at something like this but I don't know if anything has been fully completed. I recall there being a PR that addresses some things - #1315.
On the point of manually creating ticks in the game loop - that is very much possible, have a look at the `GameBase` class.

Not sure about generating shaders at runtime, maybe @ykafia can say, but you don't need the editor to write shaders (actually what is beneficial is the VS plugin).

**Comment by ykafia** [comment]
You can definitely create shaders at runtime but the best implementation we have for something similar to what you want to achieve is [VVVV's Stride.VL](https://www.youtube.com/watch?v=aG_dYEj2fN0), and here is the [source](https://github.com/vvvv/VL.Stride).
At a high level, each basic functions is wrapped in a Mixin with compose nodes for I/O and the runtime is calling the shader mixin builder to do the building of the whole graph.

**Comment by tebjan** [comment]
In VL.Stride you can find almost everything you are looking for. The only thing missing is proper integration into avalonia. This should definitely become a nuget package, if someone is successful.

**Comment by VeyDlin** [comment]
Thank you, your answers will help me a lot

I think I can create an integration in avalonia myself as soon as I figure it out

As for shaders, my program assumes that users themselves will be able to create masterpieces using a graphical interface, so I asked about the possibility of doing this from code so that I could write a wrapper for users

**Comment by ykafia** [comment]
@VeyDlin 

I think those tests can help you understand how to generate shaders from code, [here](https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Shaders.Tests/TestMixinCompiler.cs). This is the base code to compose shaders from many different pieces.

Feel free to close the issue if you found your answers answered 🙂

**Comment by tebjan** [comment]
> As for shaders, my program assumes that users themselves will be able to create masterpieces using a graphical interface, so I asked about the possibility of doing this from code so that I could write a wrapper for users

This is basically what the FUSE team has done. As a single developer, it will be hard to reach a better solution than a team of 3 has already. It might be smarter to start with their solution and build on that: https://www.thefuselab.io/

**Comment by VeyDlin** [comment]
Thanks! Now I have enough material to study

**Comment by damian-666** [comment]
just wondering the status on this and offering some ideas:

there is a new Avalonia Dock to look at ..

https://github.com/wieslawsoltes/Dock

https://github.com/AvaloniaInside/AvaloniaInside.MonoGame  ( also forked by wieslawsoltes) ..


 there are pretty rough but you can make a sort domain specific IDE with this..    might give an  teh Dock host.. s using a bitmap and might need wrangling to get it working with tabs.
if only one view its should work.  it did with monogame and its not enough for prototypoing   

https://github.com/oleg-shilo/cs-script

 the cs-script has a soft debugger for inspection that doest not block threads.  it can show a call stack via attributes and reflection.  
 
   the VVVV one might be better.. or just for shaders.
 
 and theres this..
 and https://github.com/AvaloniaUI/AvaloniaEdit
 
 i don't know , if they are practical , these are all in flux and not that active lately.  everyone is over-committed.
 
  and chatgpt need integration too..
   vs the latest API, because trained on the old stride, its code will not build. 
   
    so much tooling is changing just though it drop what i last found was alive and kickiing a few months back..  
 
 its hard to make a game with an domain specific IDE and a big debugger and a game window all on the screen..   2x 4K monitors, or a touch PC like surface ( prototype mobile games) + a 4K is needed,  and switching context is difficult..
