### ISSUE TITLE
UI Language cannot be changed

### ISSUE THREAD

**Issue by tebjan** [stride3d/stride#1714]
**Release Type**: Release

**Version**: 4.1.0.1838

**Platform(s)**: Game Studio

**Describe the bug**
UI Language cannot be changed in settings.

**To Reproduce**
1. Change UI language in settings
2. Presse save & close 
3. Restart Game Studio

Would be good to know when this stopped working.

**Expected behavior**
Language is changed.

**Screenshots**
<img width="739" alt="image" src="https://github.com/stride3d/stride/assets/1094716/154516f0-441c-4f6c-a8b3-fc9f1f37d28c">

**Comment by Jklawreszuk** [comment]
I found a potential problem!
Let's look at the result of the message.dll generated by Stride.GNU.Gettext for NET 5 (version 4.0.1.1428)

![image](https://github.com/stride3d/stride/assets/31008367/8afdd121-1b20-4b10-8611-e4df4ab49b1c)

Problem is ... that won't compile in NETCore+, only on .NET Framework runtime, because the ResourceSet has been refactored in NetCore.
```cs
///Decompiled fragment of ResourceSet in NET 6
 public class ResourceSet : IDisposable, IEnumerable
    {
        protected IResourceReader Reader = null!;

        private Dictionary<object, object?>? _table; //Changed to private
        private Dictionary<string, object?>? _caseInsensitiveTable;  // For case-insensitive lookups.

```
Also, I've looked into how it is generated and it's using NET Framework csc as a tool :/ 
But, I'm currently working on porting Stride.GNU.Gettext to NET6, so I'll let you all know on progress 😃

**Comment by Jklawreszuk** [comment]
This issue can now be closed 🙂
