### ISSUE TITLE
Entity Property Rotation Value Bug

### ISSUE THREAD

**Issue by domske** [stride3d/stride#174]
**Version**: 3.0.0.4

**Describe the bug**
The rotation values have a rounding issue. 
Set 90 degree and see 89.98 degree after reselect the entity.
This behaves on different values.

**To Reproduce**
1. Create a entity (e.g. ribbon particle)
2. Change the transform rotation to X: -90 deg.
3. Deselect the entity.
4. Select the same entity again.
5. See the X rotation value: -89.98 deg.

**Expected behavior**
The entered value should not be modified. -90 should be -90.
Maybe just a display bug. But anyway ...

**Screenshots**
![bug](https://user-images.githubusercontent.com/28209992/44946449-e7601e00-adfc-11e8-8c11-7ce683cf9c71.gif)

**Additional context**
Windows 10 64-bit

**Comment by xen2** [comment]
We store rotation in a different format (Quaternion) rather than Euler angles (as displayed in the editor) which is why there is sometimes a small change when going back and forth.
It appears only after deselecting/reselecting because we still do our best to keep the Euler version as long as the view model exists. It gets destroyed when deselected.

**Comment by xen2** [comment]
Still, it might be worth investigating, -90 to -89.98 seems quite a big difference.

**Comment by Eideren** [comment]
Fixed through #1532
