### ISSUE TITLE
*.glb asset is imported with broken mesh

### ISSUE THREAD

**Issue by delustra** [stride3d/stride#2406]
**Release Type**: GitHub 

**Version**: 4.2.0.2188

**Platform(s)**: Windows

**Describe the bug**
GLTF asset is imported incorrectly. Geometry transformations and animations are broken for certain assets. At the same time the same assets work fine in other assets viewers. 

**To Reproduce**
1. Open editor
2. Create asset '3D Model'
3. Import this model [this model](https://drive.google.com/file/d/1RmugfviPMvg3joTHwSvEXzth00OFEiZw/view?usp=sharing)
4. Hangar geometry is broken. The gates are inside the hangar.
![image](https://github.com/user-attachments/assets/493fcdb1-40fb-4d44-bad3-d310f462a1fa)

**Expected behavior**
Hangar imports with proper geometry. This how the same assets looks in the regular windows 3d asset viewer.
![image](https://github.com/user-attachments/assets/b4f7c7b1-7be2-444b-933e-8262dc412aaf)

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**

**Comment by Basewq** [comment]
I've debugged the importer with your model and it looks like the underlying assimp library isn't loading the node hierarchy properly because of duplicate names making things linked incorrectly to one another.
I imported it into blender and see your mesh objects have the same name as the bones (eg. 'door_under' is the name of both the mesh object and the bone).

As a workaround, when I renamed the bones (eg. add a _bone suffix) then re-exported it, the animations seem to work correctly.
