### ISSUE TITLE
Field containing custom class doesn't get properly deserialized

### ISSUE THREAD

**Issue by Eideren** [stride3d/stride#255]
**Release Type**: GitHub
**Version**: 3.0.0.7
**Platform(s)**: Any
**Describe the bug**
If a script component contains a field and that field is initialized by the class' constructor, the deserializer won't apply any of its serialized data. If the field is not initialized by the constructor (field is null) instead, the serializer will create the field's class and assign data as expected.

**To Reproduce**
Create a script with the following content
```
using Xenko.Engine;
public class TestSerializationIssue : ScriptComponent
{
    public float f = 0.5f;
    public TestSubClass testField = new TestSubClass();
    public class TestSubClass
    {
        public int intField;
    }
}
```
Drop it on one of the entity of your scene
Modify intField to a non-zero value
Save the scene, close and re-open it.
Look at the intField and see that it has been reset back to zero.

If you want to verify the claim that it does work when initialized as null:
After saving your scene, comment out the initialization of the field in the script.
Save it.
Close and re-open the scene and the intField should be set to the value that you set it at when you saved it.

**Expected behavior**

**Screenshots**

**Log and callstacks**

**Additional context**

I should be working on solving this issue, If you don't see a PR after 24h feel free to step in.

**Comment by xen2** [comment]
Can you try to add `[DataContract]` attribute on `TestSubClass`?

**Comment by Eideren** [comment]
@xen2 It does resolve the issue, what does DataContract imply to the engine ? Is that something required to help the serializer ?

**Comment by Kryptos-FR** [comment]
@Eideren the attribute shows that the class is serializable, which is necessary for it to be serialized into YAML.

**Comment by Eideren** [comment]
@Kryptos-FR that's not exactly how it works though, a class without that attribute still gets properly serialized (and *deserialized* if the field is not initialized), open an *.xkscene in your text editor after going through the steps described on the first post and you'll see that it contains that class' data.

**Comment by Eideren** [comment]
This isn't reflected with a game though, probably because the yaml serializer isn't taking care of that deserialization, in which case DataContract is required.
Games runs `Xenko.Core.Serialization.ClassDataSerializer` instead.

**Comment by Eideren** [comment]
Ok so what DataContract actually does is notify the non-yaml serialization system that it has to generate a serializer class for that type to be able to serialize it properly.

**Comment by Eideren** [comment]
@xen2 & @Kryptos-FR so what should we do, I could push a PR which would disable yaml serialization for types that the other serializer can't deal with ?

**Comment by xen2** [comment]
Few clarifications:
* Yaml serialization is for design time objects.
* Binary serialization is for runtime objects.
Some objects are serialized by both of them (i.e. components, scripts, etc...).

Now, concerning binary serialization:

If a member is not of a serializable type we skip it -- but it should be **issuing a warning** (during assembly processor)
Code is here: https://github.com/xenko3d/xenko/blob/releases/3.0.0.6/sources/core/Xenko.Core.AssemblyProcessor/Serializers/CecilSerializerContext.cs#L224

The idea to go with a "whitelist" approach rather than a blacklist is that otherwise we often ended up serializing unexpected stuff (esp. since it would work recursively, i.e. I remember it trying to serialize `Type` and then try to keep digging in its members and ultimately fail).

At the time, choices were:
(1) Keep blacklist but make it a compile error rather than a warning (not sure if most of our code is now compliant with that rule -- otherwise we might have to add quite a bunch of `[DataMemberIgnore]`)
(2) Whitelist approach: make `[DataMember]` necessary for each member (same, very explicit, probably thousands to add and user would probably forget them all the time in scripts)
(3) Keep current approach (only treat members that are serializable and warn+skip if one is not)

So far we didn't go with (2) because it would have involved lot of explicit attributes everywhere in the code and would have probably broke lot of engine and user code.
Not sure how much changes/impact would (1) have, might be worth switching to it at some point.

Open to opinions, and if you see any other interesting ways...
For sure it's easier to change now, before we have many more users -- but be warned that any change in this area require careful consideration and could have massive impact.

**Comment by Eideren** [comment]
It does indeed generate a warning, 'didn't notice it before as I was working on resolving #220 at the same time.
I'm not familiar enough with the engine to properly implement (1), so I'll just clarify some warnings for now.

**Comment by Eideren** [comment]
Main issue resolved, as for the discussion on the logic behind serialization attribute we never know if user fields and properties are safe and/or should be serialized, let's not serialize them by default, better safe than sorry.
