### ISSUE TITLE
Strange physical effects

### ISSUE THREAD

**Issue by jkh404** [stride3d/stride#2585]
Issue Type: Bug Report

Version: 4.2.0.2282

Platform: Please specify the platform where the issue is encountered (e.g., Windows 10, Android 9, etc.)

Describe the bug Two unusual physical effects have been observed when using a physics engine with rigid bodies:

The falling balls do not scatter as expected but instead form a wall. They only exhibit normal physical behavior when a larger ball is used to collide with them.
The falling balls stack on top of each other instead of spreading out as anticipated.
To Reproduce Steps to reproduce the behavior:

Launch the application.
Create a new physics simulation scene with multiple balls that have rigid body properties.
Set the scene parameters so that the balls begin to fall from a certain height.
Observe the behavior of the falling balls.
Specific steps to reproduce the problem:

For the issue with balls forming a wall: a. Place multiple balls at the top of the scene. b. Observe the balls falling and forming a wall. c. Collide with a larger ball to observe the change in physical behavior.
For the issue with balls stacking on top of each other: a. Place multiple balls at the top of the scene with enough space to fall. b. Observe the stacking behavior of the balls after they fall.
Expected behavior

The balls should scatter as they fall instead of forming a wall.
The balls should not stack on top of each other when falling but should maintain some distance.
Logs and Callstacks If available, please attach any logs or callstacks here (preferably uploaded as a .txt file using GitHub’s drag-and-drop feature).

Additional context Add any other context about the problem here. For example, does the issue occur under specific conditions or is it related to certain settings?

![Image](https://github.com/user-attachments/assets/5603c3c5-9a9e-4462-847a-6680749ce092)
![Image](https://github.com/user-attachments/assets/9ddfb3b2-af84-41c4-b25c-153c89c47ab8)

**Comment by Nicogo1705** [comment]
Thank you for the detailed report!

The behavior you're observing is actually expected due to the nature of perfect spheres in physics simulations. A perfectly spherical object, when perfectly centered, will balance on top of another sphere without rolling off. This balance occurs because there are no external forces causing them to lose equilibrium.  
(Their centers of mass are perfectly aligned with the Y-axis, so they can't generate X or Z reaction forces.)

To address the issues:

1. **For scattering:** Try introducing small offsets in positions or perpendicular forces to the spheres when they are spawned. This will break the perfect symmetry and encourage a more natural scattering effect.
2. **Let it scatter:** If you're using BEPU Physics, ensure that the spheres are marked as "awake" (either by setting `awake = true;` or defining the `sleepThreshold` to a negative value). Sometimes, objects may go to sleep in the physics engine to optimize performance, which can prevent them from losing balance or behaving dynamically.

These adjustments should help achieve the expected behavior. Let us know if further clarification or assistance is needed!

**Comment by jkh404** [comment]
Thanks for your answer, I understand.
Next I will close the Issue.
