### ISSUE TITLE
I cant play the game, when I press play, it builds and then nothing happens!

### ISSUE THREAD

**Issue by XenkoGame** [stride3d/stride#51]

**Comment by xen2** [comment]
Thanks for the report.
There's an "Output" pane in the lower area of the editor.
Could you attach the output after pressing the `Build and Run` button and waiting for the button to be not greyed out anymore please?

**Comment by NewNodeGames** [comment]
Same here. Here my report:
[(0,0)]: Info: Patch for assembly [ThirdPersonPlatformer.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
[(0,0)]: Info: ThirdPersonPlatformer.Game -> C:\Users\usuario\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Game\bin\Debug\net461\ThirdPersonPlatformer.Game.dll
[(0,0)]: Info: Patch for assembly [ThirdPersonPlatformer.Windows, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
[(0,0)]: Info: ThirdPersonPlatformer.Windows -> C:\Users\usuario\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\Bin\Windows\Debug\ThirdPersonPlatformer.Windows.exe
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
[(0,0)]: Info: Waiting 100ms for the proxy server to start and connect to it
Info: BuildEngine arguments: --disable-auto-compile --project-configuration Debug --platform=Windows --profile=Windows --project-configuration=Debug --output-path=C:\Users\usuario\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\Bin\Windows\Debug\data --build-path=C:\Users\usuario\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Windows\..\Cache\data --package-file=C:\Users\usuario\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Windows\..\ThirdPersonPlatformer.xkpkg --log-pipe=net.pipe://localhost/Xenko.Core.Assets.Editor.ddc19287-1e16-4815-97f9-a6a091a83012 --verbose
Info: Starting builder.
Info: Processing convex hull generation, this might take a while!
Info: Node generated 1 convex hulls
Info: For a total of 114 vertexes
Info: Processing convex hull generation, this might take a while!
Info: Node generated 1 convex hulls
Info: For a total of 19 vertexes
Info: Processing convex hull generation, this might take a while!
Info: Node generated 1 convex hulls
Info: For a total of 110 vertexes
Error: Exception in command [Skybox] SkyboxAsset: d7887972-d7fe-4667-9887-3aa59cb3d38b: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: El parámetro no es correcto.

   en SharpDX.Result.CheckError()
   en SharpDX.Direct3D11.Device.CreateShaderResourceView(Resource resourceRef, Nullable`1 descRef, ShaderResourceView sRViewOut)
   en Xenko.Graphics.Texture.GetShaderResourceView(ViewType viewType, Int32 arrayOrDepthSlice, Int32 mipIndex)
   en Xenko.Graphics.Texture.InitializeFromImpl(DataBox[] dataBoxes)
   en Xenko.Graphics.Texture.InitializeFrom(Texture parentTexture, TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas)
   en Xenko.Rendering.ComputeEffect.GGXPrefiltering.RadiancePrefilteringGGXNoCompute.DrawCore(RenderDrawContext context)
   en Xenko.Rendering.RendererBase.Draw(RenderDrawContext context)
   en Xenko.Assets.Skyboxes.SkyboxGenerator.Compile(SkyboxAsset asset, SkyboxGeneratorContext context)
   en Xenko.Assets.Skyboxes.SkyboxAssetCompiler.SkyboxCompileCommand.DoCommandOverride(ICommandContext commandContext)
   en Xenko.Core.BuildEngine.CommandBuildStep.<StartCommand>d__21.MoveNext()
Error: BuildStep [Skybox] SkyboxAsset: d7887972-d7fe-4667-9887-3aa59cb3d38b failed.
Error: Exception in command [Skybox] SkyboxAsset: d7887972-d7fe-4667-9887-3aa59cb3d38b: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: El parámetro no es correcto.

   en SharpDX.Result.CheckError()
   en SharpDX.Direct3D11.Device.CreateShaderResourceView(Resource resourceRef, Nullable`1 descRef, ShaderResourceView sRViewOut)
   en Xenko.Graphics.Texture.GetShaderResourceView(ViewType viewType, Int32 arrayOrDepthSlice, Int32 mipIndex)
   en Xenko.Graphics.Texture.InitializeFromImpl(DataBox[] dataBoxes)
   en Xenko.Graphics.Texture.InitializeFrom(Texture parentTexture, TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas)
   en Xenko.Rendering.ComputeEffect.GGXPrefiltering.RadiancePrefilteringGGXNoCompute.DrawCore(RenderDrawContext context)
   en Xenko.Rendering.RendererBase.Draw(RenderDrawContext context)
   en Xenko.Assets.Skyboxes.SkyboxGenerator.Compile(SkyboxAsset asset, SkyboxGeneratorContext context)
   en Xenko.Assets.Skyboxes.SkyboxAssetCompiler.SkyboxCompileCommand.DoCommandOverride(ICommandContext commandContext)
   en Xenko.Core.BuildEngine.CommandBuildStep.<StartCommand>d__21.MoveNext()
Error: BuildStep [Skybox] SkyboxAsset: d7887972-d7fe-4667-9887-3aa59cb3d38b failed.
Skybox(0,0): Error: Asset [Skybox] failed to compile
Error: BuildStep Asset build steps [SkyboxAsset:'Skybox'] (2 items) failed.
Error: BuildStep Build step list (449 items) failed.
Error: BuildStep Build step list (1 items) failed.
Error: Build finished in 940 steps. Command results: 0 succeeded, 936 up-to-date, 4 failed, 0 not triggered due to previous failure.
Error: Build failed.
Info: Generate bundles: Scan assets and their dependencies...
Info: Generate bundles: Assign assets to bundles...
Error: Unhandled exception. Could not find asset Skybox for bundle default
[(0,0)]: Info: RunTime 00:00:13.45
[C:\Users\usuario\.nuget\packages\xenko\3.0.0.1\Targets\Xenko.targets(374,5)]: Error: El comando ""C:\Users\usuario\.nuget\packages\xenko\3.0.0.1\Bin\Windows\Xenko.Core.Assets.CompilerClient.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --profile=Windows --project-configuration=Debug --output-path="C:\Users\usuario\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\Bin\Windows\Debug\data" --build-path="C:\Users\usuario\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Windows\..\Cache\data" --package-file="C:\Users\usuario\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Windows\..\ThirdPersonPlatformer.xkpkg" --log-pipe="net.pipe://localhost/Xenko.Core.Assets.Editor.ddc19287-1e16-4815-97f9-a6a091a83012" --verbose" salió con el código 1.

**Comment by Eideren** [comment]
No logs provided in two years, I don't think he'll get back to us. As for @NewNodeGames, it might be a graphics API issue, try again under dx11. 
I'll just close this off anyway given the lack of logs, feel free to create a new one if you're still there though !
