### ISSUE TITLE
Projects with Stride.Voxels as a dependency cannot be built

### ISSUE THREAD

**Issue by WhyPenguins** [stride3d/stride#683]
GitHub master(4.0.0.1-beta02), Windows

Firstly, sorry for never getting back after the merge, thanks so much for helping it through!

There's a problem though. Adding Stride.Voxels as a dependency to a project causes it to fail when building; everything works fine in the editor however. It seems that the asset compiler can't deserialize any of the classes in that module.

**To Reproduce**
1. Create a project (I usually use the FirstPersonShooter template)
2. Confirm it builds and runs
3. Add Stride.Voxels as a dependency
4. It no longer builds

**Expected behavior**
Probably should still build.

**Log and callstacks**
[VoxelsBuildFail.txt](https://github.com/stride3d/stride/files/4555937/VoxelsBuildFail.txt)

Thanks for any help!

**Comment by tebjan** [comment]
I've experienced the same... Wasn't sure whether it's a problem in my side.

**Comment by jeske** [comment]
I'm very new to stride engine, so I don't know if any of this will be useful, but here are my observations so far...

At first glance, it looks to me like the problem is the [buildengine](https://github.com/stride3d/stride/tree/master/sources/buildengine)does not have Stride.Voxels in it's environment, so it can't access it's classes for (de)serialization when reading the asset files during the asset build.

I assume Stride.Voxels must be capable of doing (de)serialization, since how else would it save and load Stride Studio save files?

And so my current question is...

**Where does the buildengine load dependent assemblies during the build process?**

Below are the hard-coded references in the build engine `csproj`.. I don't know how the builder works, but this doesn't seem like all of what it would need to process any assets, so I assume it is picking up other assembly dependencies somehow...
```<ItemGroup>
    <ProjectReference Include="..\..\core\Stride.Core\Stride.Core.csproj" />
    <ProjectReference Include="..\..\core\Stride.Core.IO\Stride.Core.IO.csproj" />
    <ProjectReference Include="..\..\core\Stride.Core.MicroThreading\Stride.Core.MicroThreading.csproj" />
    <ProjectReference Include="..\..\core\Stride.Core.Serialization\Stride.Core.Serialization.csproj" />
    <ProjectReference Include="..\Stride.Core.BuildEngine.Common\Stride.Core.BuildEngine.Common.csproj" />
  </ItemGroup>
```

**Comment by jeske** [comment]
This video is helpful for setting up a working voxel project

[Howto setup Real Time Voxel Global Illumination in Stride3D 4.0.0.1 beta2 - YouTube](https://www.youtube.com/watch?v=NEMZ_HJzJ7w&t=67s)

**Comment by xen2** [comment]
`Stride.Voxels` should now be properly loaded. Still not sure how it could have been working on my PC before, there was definitely some functionality missing.

There's still one issue left to easily setup runtime plugins such as VoxelGI:
A GameStudio restart is needed, otherwise the project won't run directly out of the box from GameStudio using F5
Everything else is OK, including creating Graphics Compositor (without GameStudio restart).

**Comment by jeske** [comment]
I'm still getting an error trying to build an existing VXGI project with head-of-tree Stride.

Building inside Stride Editor yields...

```
[C:\Users\david\.nuget\packages\stride.core.assets.compilerapp\4.0.0.1-beta02-0926\buildTransitive\Stride.Core.Assets.CompilerApp.targets(68,5)]: Error: The command ""C:\Users\david\.nuget\packages\stride.core.assets.compilerapp\4.0.0.1-beta02-0926\buildTransitive\..\lib\net472\Stride.Core.Assets.CompilerApp.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --project-configuration=Debug --property:RuntimeIdentifier=win7-x86 --output-path="C:\Users\david\Documents\Stride Projects\ThirdPersonPlatformer3\Bin\Windows\Debug\data" --build-path="C:\Users\david\Documents\Stride Projects\ThirdPersonPlatformer3\ThirdPersonPlatformer3.Windows\obj\stride\assetbuild\data" --package-file="C:\Users\david\Documents\Stride Projects\ThirdPersonPlatformer3\ThirdPersonPlatformer3.Windows\ThirdPersonPlatformer3.Windows.csproj" --log-pipe="StrideCoreAssetsEditor.858164b2-2197-4aee-aa11-828b326d3b1b" --verbose" exited with code 1.
```

Building in VS2019 yields...

![image](https://user-images.githubusercontent.com/15093/80927767-e5c6c600-8d54-11ea-81a0-191c65043bc7.png)

**Comment by xen2** [comment]
@jeske 
You compiled from `master` and you can see `4.0.0.1-beta2` in title bar without the -0926, right?
I think it's because I didn't bump to `-beta3` so it considers the released version a future version, doesn't update project and keep using those nugets.
Let me bump it.
