### ISSUE TITLE
Why is the Twitter account blocked?

### ISSUE THREAD

**Issue by aivascu** [stride3d/stride#704]
# Question and/or Comment
I have discovered the engine just recently. I am not aware of the engine's history but many things are raising questions for me.
Why is the Twitter account blocked (https://twitter.com/stride3d?lang=en)? 
Why is the site periodically down (https://stride3d.net)?
Why is the setup detected as malware by AV?
Why isn't the engine discussed as much in the media (considering the features it boasts)?

**Comment by Eideren** [comment]
* This is the right account: https://twitter.com/stridedotnet, someone took stride3d before we could.
* It hasn't been down for me, next time try to use services like ``isitdown`` to check if it's on your side.
* See the thread you already commented in (#671) 
* There's some kinks to iron out but more likely because it is still a fairly young engine and right now it is less user friendly towards artists than other engines.

**Comment by aivascu** [comment]
@Eideren thank you for the reply.
The answer to the first question means there is a bug in the docs website. 
The link in the [docs](https://doc.stride3d.net/latest/en/manual/index.html) says its the account I mentioned in the question.
I checked the repos under the stride account and have been able to find the wrong twitter account only in the `_config.yml` file of the `stride-website` repo. 
There's some more places that mention the old xenco contacts, but I guess that comes with a huge rename like that.
