### ISSUE TITLE
consider using gamedev.stackexchange.com for Q&A

### ISSUE THREAD

**Issue by jeske** [stride3d/stride#706]
This is a tracking issue for our discussion on using gamedev.stackexchange.com as a Q&A site..

I think specifically using gamedev would be a great idea, as it would provide visibility for Stride, and connect with other talented game developers.

There is currently a "Xenko" tag on gamedev. It takes [300 gamedev reputation to make a new "Stride" tag](https://gamedev.stackexchange.com/help/privileges/create-tags), and once made it's possible to [make Xenko a synonym for Stride](https://math.meta.stackexchange.com/questions/11162/what-is-the-difference-between-merging-two-tags-and-synonymizing-two-tags) and link them together. 

It's easy to [link directly to the "ask a question" page with tags filled in](https://gamedev.stackexchange.com/questions/ask?tags=StrideGameEngine). Here is an example with Xenko and C# as tags prefilled.

https://gamedev.stackexchange.com/questions/ask?tags=xenko,C%23

If we decide to go this route, I think the next steps are:

1) figure out where to place a direct question link in a visible place
2) somehow display [unanswered stride questions](https://gamedev.stackexchange.com/search?q=xenko+answers%3A0) (or a count) on the stride website
3) get the Stride tag made, make sure it's in the above two links/features
4) once there are some questions filed on the stride tag, ask for Xenko to be made a synonym of stride

**Comment by xen2** [comment]
Sounds good to me, let's go with gamedev.stackexchange.com!
It's also important to promote it properly to make sure everything support-wise goes there.
We could add a link to it on those places:
- Website community page https://stride3d.net/community/
- Forums (either banner or explanation in grayed out initial text when creating post) so that people who were thinking to ask support questions know about its existence.
- Icon in launcher
- Later: Possibly a question mark icon in the Game Studio top-right corner?

**Comment by xen2** [comment]
If somebody has 300+ reputation, feel free to create the `stride` tag please!

**Comment by StefanJanssen95** [comment]
In the meantime the tag has been created: https://gamedev.stackexchange.com/tags/stride

**Comment by herocrab** [comment]
This is now a reality, correct? Can we close out this issue?

**Comment by tebjan** [comment]
For now, we use: https://github.com/stride3d/stride/discussions
