### ISSUE TITLE
Fullscreen mode cause exception if game window is not focused

### ISSUE THREAD

**Issue by HordeResurrection** [stride3d/stride#724]
**Release Type**: Official Release

**Version**: 3.1.0.1

**Platform(s)**: Windows

**Describe the bug**
Switching to full screen mode cause `SharpDX.SharpDXException` if game window lost focus early. See below.

**To Reproduce**
1. Run the game: [FullscreenIssueExample.zip](https://github.com/stride3d/stride/files/4626100/FullscreenIssueExample.zip)
2. Switch focus to another window. Simply click to other window
3. Wait for an exception

Demonstration: [2020-05-14.gif](https://user-images.githubusercontent.com/65279361/81897824-0ea25300-95c0-11ea-815c-a5ca78805b6d.gif)

Sample reproducing code (part of `FullscreenIssueExample.zip`):
```
    public class MyGame : Game
    {
        protected override void Initialize()
        {
            base.Initialize();

            GraphicsDeviceManager.IsFullScreen = true;
            GraphicsDeviceManager.ApplyChanges();
        }
    }
```

**Expected behavior**
I want to activate full screen mode.
Or I want to cancel full screen mode if it's impossible.

**Log and callstacks**
```
SharpDX.SharpDXException: 'HRESULT: [0x887A0022], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_CURRENTLY_AVAILABLE/NotCurrentlyAvailable], Message: A resource is not available at the time of the call, but may become available later.

This exception was originally thrown at this call stack:
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.SetFullscreenState(RawBool fullscreen, Output targetRef)
   at Xenko.Graphics.SwapChainGraphicsPresenter.CreateSwapChainForDesktop(IntPtr handle)
   at Xenko.Graphics.SwapChainGraphicsPresenter.CreateSwapChainForWindows()
   at Xenko.Graphics.SwapChainGraphicsPresenter..ctor(GraphicsDevice device, PresentationParameters presentationParameters)
   at Xenko.Games.GamePlatform.CreateDevice(GraphicsDeviceInformation deviceInformation)
   at Xenko.Games.GamePlatform.ChangeOrCreateDevice(GraphicsDevice currentDevice, GraphicsDeviceInformation deviceInformation)
   at Xenko.Games.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation newInfo)
   at Xenko.Games.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean forceCreate)
   at Xenko.Games.GameBase.InitializeBeforeRun()
   at Xenko.Games.GamePlatform.OnInitCallback()
   at Xenko.Games.GameWindowWinforms.Run()
   at Xenko.Games.GameBase.Run(GameContext gameContext)
   at FullscreenIssue.Windows.FullscreenIssueApp.Main(String[] args)
```
or [callstack.txt](https://github.com/stride3d/stride/files/4626121/callstack.txt)

**Additional context**
There is a same issue in MonoGame (thanks to SolarChrome which found it): https://github.com/MonoGame/MonoGame/issues/4148

**Comment by Kryptos-FR** [comment]
I can't reproduce. Every time I switch to another window, the game becomes windowed and I don't get the exception.

**Comment by HordeResurrection** [comment]
No, I use one monitor.
Game window must lost focus before as game perform fullscreen switching.
I can to record a video.

**Comment by HordeResurrection** [comment]
![2020-05-14_08-45-45](https://user-images.githubusercontent.com/65279361/81897573-98055580-95bf-11ea-8148-bf1974851c3e.gif)

How to reproduce

**Comment by Kryptos-FR** [comment]
Even with those steps I can't reproduce. Could it be your PC is relatively slow or the CPU is busy?

**Comment by HordeResurrection** [comment]
I reproduced bug at several PC. Both Windows 8/10.

> or it starts windowed

I want at least same behavior but can't achieve it

**Comment by Kryptos-FR** [comment]
Are you running on a laptop (that has an integrated GPU)? Maybe the timings are different when it tries to use the integrated GPU instead of the graphic card. That would be a hint why I can't reproduce if my card is very quick to create the graphics context, or something like that.

It does look like something is not properly initialized when the focus is lost. I don't know if we could force the window to activate for a while to prevent loosing focus until everything is initialized (low-level only). Maybe there are some win32 hooks that can achieve that...

**Comment by HordeResurrection** [comment]
I am running on a common PC. It's so no top configuration but GTA 5 and other games works fine.
```
i5-3450 - 4x 3.50 GHz
RAM DDR3 - 8 Gb
Video GTX 760 - 2 Gb
```

You can add `Thread.Sleep(1000);` in `Game.Initialize()`. One may it's help

**Comment by Eideren** [comment]
> You can add ``Thread.Sleep(1000);`` in ``Game.Initialize()``. One may it helps

Uh, what do you mean ? Forcing a sleep as a work around ? If we *really* have to work around this issue we should detect when that exception will occur or catch that exception and postpone changing the fullscreen state until we hit a point where it would be safe to do so.

**Comment by Kryptos-FR** [comment]
I managed to reproduce it a few times. And I dug a bit into the code and if I do a hackish workaround in `SwapChainGraphicsPresenter.CreateSwapChainForDesktop(IntPtr)` I can display a borderless window instead of crashing.

```diff
// Switch to full screen
-newSwapChain.IsFullScreen = true;
+try
+{
+    newSwapChain.SetFullscreenState(true, null);
+}
+catch (SharpDXException ex)
+{
+   return newSwapChain;
+}
```

Obviously, this is not a fix but it shows that this error is not fatal. Furthermore, the documentation of `SwapChain.SetFullscreenState()` explicitly states that we should expect to sometimes get an exception that the device is not ready but might be later (hence this error code we see in the exception message: "DXGI_ERROR_NOT_CURRENTLY_AVAILABLE/NotCurrentlyAvailable").

**Comment by HordeResurrection** [comment]
> Forcing a sleep as a work around ?

Oh no.. It is way to reproduce bug.

I had launched beta test today. Some gamers had same exception during game is running.

I can't catch exception because it throws between `Initialize()` and `LoadContent()`. 
I can only catch it here:
```
try
{
    game.Run();
}
catch (Exception ex)
{
    [...]
}
```
But it useless

**Comment by HordeResurrection** [comment]
> I can display a borderless window instead of crashing.

It can be good solution in my case

**Comment by Basewq** [comment]
I don't know if this would help, but I would remove `GraphicsDeviceManager.ApplyChanges();` in your initialize method, because GameBase immediately recreates the device in the next call
https://github.com/stride3d/stride/blob/6f7a8a099b7f4e5ca92c42078d79771554721bbb/sources/engine/Stride.Games/GameBase.cs#L349-L352

**Comment by Kryptos-FR** [comment]
@Basewq that won't change anything. I tried moving that property change in different method override or callback. It can still happen if the app loses focus while the fullscreen change happens.

**Comment by HordeResurrection** [comment]
Do not use fullscreen in exclusive move. Use windowed borderless mode instead
