### ISSUE TITLE
DataMember order incorrect?

### ISSUE THREAD

**Issue by azeno** [stride3d/stride#735]
Is this supposed to be correct? Has the same offset as previous property. The property is also not checked in hash code as well as in equality.

https://github.com/stride3d/stride/blob/273dfddd462fd3746569f833e1493700c070b14d/sources/engine/Stride.Rendering/Rendering/Materials/MaterialSpecularMicroFacetModelFeature.cs#L41

**Comment by xen2** [comment]
Sorry for late answer.
This `30` is probably a copy-paste mistake.
However, in practice, `DataMember` number conflict is not going to cause any issue (we use a stable sort).

Also, since we use Cecil and IL order seems deterministic, it's probably not that useful anymore (except maybe in the far-fetched case somebody wants an inheriting type to interleave members with its base type in nice order for Yaml?)
