### ISSUE TITLE
Instancing crashes if instancing added before model component

### ISSUE THREAD

**Issue by johang88** [stride3d/stride#813]
**Release Type**: Github
**Describe the bug**
Adding an instancing component and then a model component crashes the instancing processor.

**To Reproduce**
1. Add instancing component to an entity,
2. Add model component to the same entity
3. Exception time

**Expected behavior**
It should not crash.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
![image](https://user-images.githubusercontent.com/204513/88969397-15805e00-d2b1-11ea-9e7e-2a0adea7921d.png)

**Log and callstacks**
[stacktrace.txt](https://github.com/stride3d/stride/files/5003587/stacktrace.txt)

**Comment by MechaTechnica** [comment]
I cannot reproduce this.
No crash after adding instancing, followed by model component to an entity:
![image](https://user-images.githubusercontent.com/4530760/100787480-fedf4480-3413-11eb-9e37-0016595279ad.png)

**Comment by Basewq** [comment]
This is a subtle bug.
It crashes on this line:
https://github.com/stride3d/stride/blob/f7494f8be926b42a7e882c4a085331672ae97af3/sources/engine/Stride.Engine/Engine/Processors/InstancingProcessor.cs#L173
because `modelRenderProcessor` can be null in a subtle case due to how it's stored by this line:
https://github.com/stride3d/stride/blob/f7494f8be926b42a7e882c4a085331672ae97af3/sources/engine/Stride.Engine/Engine/Processors/InstancingProcessor.cs#L210

The issue is if you start with a completely empty scene (technically a scene without any entities with a `ModelComponent`), then `ModelRenderProcessor` does not exist yet, so adding `InstancingComponent` will create `InstancingProcessor` without `ModelRenderProcessor` existing.

Not sure what's the correct way of solving processor dependency, two ways I can think of to solve this:
1. Add `modelRenderProcessor ??= EntityManager.GetProcessor<ModelRenderProcessor>();` in `OnEntityComponentAdding`
2. `new ModelRenderProcessor()` and `EntityManager.Processors.Add(...)`  in `OnSystemAdd` if the first retrieval is null.

@tebjan Any other solutions or input?
