### ISSUE TITLE
CustomShader compile error on game startup

### ISSUE THREAD

**Issue by CharlesWoodhill** [stride3d/stride#816]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Release

**Version**: Version number and/or git branch
Stride 4.0.0.1-beta04-1207

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows

**Describe the bug**
Using custom shader crashes on game start

**To Reproduce**
1. create a simple shader (see below, extension changed from sdsl to txt) it will compile in VStudio
2. create a material using the shader
3. apply the material to any model (cube, sphere.)
4. start the game

**Expected behavior**
no crash, render the model in the color defined in the shader

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
[ShaderIssueLog.txt](https://github.com/stride3d/stride/files/5014722/ShaderIssueLog.txt)

**Additional context**
[SimpleShader.txt](https://github.com/stride3d/stride/files/5014741/SimpleShader.txt)

**Comment by CharlesWoodhill** [comment]
Compiling myself seem to work (tested with a simple triangle)
````
            string rootPath = simulation.RootFileSystem.RootPath;
            IVirtualFileProvider fp = new Stride.Core.IO.FileSystemProvider(rootPath, "");
            EffectCompiler compiler = new EffectCompiler(fp);
            ShaderClassString shaderSource = new ShaderClassString("Test1Shader", Shaders.Test1.Source);
            CompilerParameters shaderCompilerParams = new CompilerParameters { EffectParameters = { Platform = GraphicsDevice.Platform} };

            CompilerResults compilerResults = compiler.Compile(shaderSource, shaderCompilerParams);
            compilerResults.Bytecode.AwaitResult();
            Test1.Bytecode = compilerResults.Bytecode.Result.Bytecode;
````

**Comment by Eideren** [comment]
Materials are not made out of one monolithic shader they are instead composed of multiple shaders each one computing and providing data for the context in which it is used. And so, the material system expects of the shader you feed it with to derive from specific classes so that it can call the right method on that shader for the context in which it is used.
For example, a shader set to the DiffuseMap entry on the material has to derive from ``ComputeColor``, to 'provide' the diffuse color you override ``override float4 Compute()`` to return whatever color you want to set for that fragment, the manual goes in more depth on this subject https://doc.stride3d.net/latest/en/manual/graphics/effects-and-shaders/custom-shaders.html

Closing this off but feel free to open a new one if you think that we should clarify that exception or if I missed something else
