### ISSUE TITLE
Game Studio doesn't show tooltip for public properties that have <userdoc> or <summary>

### ISSUE THREAD

**Issue by Grafcube** [stride3d/stride#917]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1317

**Platform(s)**: Windows

**Describe the bug**
When `<userdoc>` is added to a public property, game studio should show the text when the mouse is over that property in the Property Grid. But it remains blank. Intellisense in Visual Studio shows the text as expected when using `<summary>`.

**To Reproduce**
1. Attach script to Entity.
2. Add public property in script.
3. Add `<userdoc>` in XML comment above the property with text.

**Expected behavior**
Game studio shows text when hovering over property.

**Screenshots**
![Screenshot 2020-11-20 143720](https://user-images.githubusercontent.com/34889224/99781590-0bbf8680-2b3e-11eb-8785-14c4eb845c48.png)
![Screenshot 2020-11-20 143807](https://user-images.githubusercontent.com/34889224/99781603-0feba400-2b3e-11eb-9de7-1155f624fa7d.png)

**Log and callstacks**
None

**Additional context**
Maybe game studio could also show the text in `<summary>` so that using both is unnecessary.

**Comment by AmbulantRex** [comment]
It looks like it should be using a usrdoc file in the output path with that information. Generating the documentation and outputting it into that path won't work as it's in an XML format and the code doesn't parse XML, it simply looks for a key-value pair separated by '=' like this:

```
F:Stride.Core.Mathematics.RectangleF.X=The beginning of the rectangle along the Ox axis.
F:Stride.Core.Mathematics.RectangleF.Y=The beginning of the rectangle along the Oy axis.
F:Stride.Core.Mathematics.RectangleF.Width=The width of the rectangle.
F:Stride.Core.Mathematics.RectangleF.Height=The height of the rectangle.
```

There is another part to this problem. The auto selection of the current package finds the first executable, sometimes this is a Tests project (I'll be making a different bug for that) in:

https://github.com/stride3d/stride/blob/922ba8bdaa3ea4d2ca9be288a5b5df6a0e48e3bf/sources/editor/Stride.Core.Assets.Editor/ViewModel/SessionViewModel.cs#L496-L503

regardless it seems that the executable project types aren't getting their location set correctly on the model which results in the UserDocumentationService being unable to locate the usrdoc file even if we did generate it:

https://github.com/stride3d/stride/blob/273dfddd462fd3746569f833e1493700c070b14d/sources/editor/Stride.Core.Assets.Editor/Services/UserDocumentationService.cs#L115-L147

So the questions I have are:
1) Can we support the default <assembly>.xml file which contains the xml docs?
2) Can we make package selection manual and save the result rather than guessing?
3) Why don't executable projects have a location, but library projects totally do?

**Comment by xen2** [comment]
> Can we support the default .xml file which contains the xml docs?
It was a while ago so not sure, but I think the reason was that the .xml format is quite large/slow to parse.

> Can we make package selection manual and save the result rather than guessing?
Sure, that would be a good idea.

> Why don't executable projects have a location, but library projects totally do? Is it just finding the first project file and giving that a location? Why not all of them if so?
Initially we assumed any class used in the GameStudio would come from a library due to portability reasons (i.e. we can't load iOS/Android projects at runtime, or a .NET Core project from .NET Framework GameStudio).
However, it was recently being discussed/considered to allow to load the executable project (with the restriction that Game Studio runtime can load executable project, i.e. .NET Core GameStudio can only load .NET Core executable).

**Comment by AmbulantRex** [comment]
> It was a while ago so not sure, but I think the reason was that the .xml format is quite large/slow to parse.

It can be, for sure. UserDocumentationService can cache the result currently, but that initial delay could be jarring. I have a sample I put together that I could show in a draft PR. I'll need to find a solution to the empty location problem before it's ready to rock though.

**Comment by manio143** [comment]
To generate `usrdoc` file with the AssemblyProcessor you can specify the following in your csproj.
```xml
<GenerateDocumentationFile>true</GenerateDocumentationFile>
<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(MSBuildProjectName).xml</DocumentationFile>
```
But even with it generated it hasn't been loaded in GameStudio for my project.
