### ISSUE TITLE
.Net Core 3.1 not being targetted by Windows project

### ISSUE THREAD

**Issue by thargy** [stride3d/stride#934]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1317

**Platform(s)**: Windows

**Describe the bug**
When creating a .NET Core 3.1 solution, the target framework of the root Windows Project is actually set to `net461`.

**To Reproduce**
Create a new solution supposedly targeting .NET Core, check the project's target framework.

**Comment by manio143** [comment]
This has also been fixed in #910 for .NET Core 3.1, but needs to be looked into again for .NET 5. The idea is that we should target the same framework that the GameStudio has been launched with.
https://github.com/stride3d/stride/blob/d0722c6fe6e2b26de5cbfd4f295576da3be98892/sources/engine/Stride.Assets/Templates/ProjectTemplateGeneratorHelper.cs#L123-L127

**Comment by thargy** [comment]
I'll close this as a duplicate of #910.
