### ISSUE TITLE
Input.HasGamePad returns false in latest beta

### ISSUE THREAD

**Issue by thargy** [stride3d/stride#939]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1341

**Platform(s)**: Windows

**Describe the bug**
When upgrading to latest beta and .NET 5.0, the XBoxOne Controller stopped being detected with `Input.HasGamePad` returning false.

**To Reproduce**
Upgrade project.

**Expected behavior**
No other changes made to code, so controller should continue to work.

**Additional context**
I notice that a number of pull requests relating to changes to the `InputManager` are included in this beta.  [This commit](https://github.com/stride3d/stride/pull/922/commits/9f50274aa003f07cd073dd81ab14d62fd8cfda85) from [this PR](https://github.com/stride3d/stride/pull/922) may be a potential cause?

**Comment by azeno** [comment]
The game pads come in through the `InputSourceWindowsXInput`. It gets added in `InputManager.AddSources()`. Here is a comparison of how it was before my changes with the relevant line highlighted:
https://github.com/stride3d/stride/compare/b33b96c319f6a558b3a7410f829adfef745f0a0b...6562b27f6e1b803f727322a7105b41b09b9cfe12#diff-2cc92d5bcd4923e7e4d74cbef2ccc1f1ef69e8aeaea06a86cf8aae2ca3e1cb2bL611

For `InputSourceWindowsXInput` it looks pretty much the same to me. So I wonder whether it's about the compile flags?

The compile flags of the condition `if STRIDE_PLATFORM_WINDOWS && (STRIDE_UI_WINFORMS || STRIDE_UI_WPF)` are set for `net461` and `net5.0-windows`.

What is the `TargetFramework` in your csproj file? Sadly I can't check locally how a new game project looks like with net5 because of some package incompatibility - on restore it complains that the template package isn't compatible with net5. But that's another issue I guess.

**Comment by thargy** [comment]
Thanks @azeno,

I thought it might be something to do with the compilation flags, just wasn't sure where they were defined!  It was a manual project update so, I update both the core project at windows project to target `net5.0`, which worked.  I should have thought of using `net5.0-windows` on the main project, which does fix the problem.

**Comment by thargy** [comment]
Hi @azeno,

I'm reopening this as I'ver reverted to `netcoreapp3.1` and can confirm that, although `InputSourceWindowsXInput.IsSupported()` would return `true` if called (I duplicated the logic to test), the XInput isn't being added.

I manually added
```
    <STRIDE_PLATFORM_WINDOWS>true</STRIDE_PLATFORM_WINDOWS>
    <STRIDE_UI_WINFORMS>true</STRIDE_UI_WINFORMS>
```
to the project file, and that didn't help either.

**Comment by thargy** [comment]
Yes,

However, we probably shouldn't just drop netcoreapp3.1 when adding net5.0 as appears to have been done.  Particularly as there have been issues with net5.0.

**Comment by xen2** [comment]
You can still revert back to previous version in launcher.
We'd rather avoid supporting multiple version, esp. since this intermediate 3.1 was only released during a beta.

**Comment by thargy** [comment]
@xen2, the launcher itself has .netcore 3.1 removed, so, although you can revert to a previous version, it's not easy to revert the launcher itself to a previous version once it's been updated.  You can uninstall, but it's not easy to get a previous installer version unless you happen to have it.  I just went through that experience and it's not easy.

**Comment by xen2** [comment]
@thargy The launcher framework dropdown should refresh if you choose a different minor version (i.e. `4.0.0.1-beta04-1317`)

**Comment by xen2** [comment]
This feature is maybe not obvious: you can select any version (installed or not) and then do the usual operation on it
![image](https://user-images.githubusercontent.com/527565/101631145-2e99d800-3a24-11eb-969d-8ce7a688dbc6.png)

**Comment by thargy** [comment]
Yes, but the `.NET 4.7.2` dropdown for the editor doesn't include .Net Core 3.1 any more, and the .Net 4.7.2 build cannot open .Net 5 projects and causes issues when building the .Net Core 3.1 project assets (at least in my scenario it did).

**Comment by thargy** [comment]
OK so this was caused by `.NET Core 3.1` support being removed from `beta04-1341`, so targeting that framework doesn't set up the requirements used to enable gamepad support.  Fundamentally, relying on the `STRIDE_PLATFORM_WINDOWS` and `STRIDE_UI_WINFORMS` properties is entirely reasonable, and the fault is with the build system not reliably setting them.
