### ISSUE TITLE
Cannot add more items to dictionary in the inspector

### ISSUE THREAD

**Issue by Shpendicus** [stride3d/stride#959]
**Release Type**: Official Release/GitHub 

**Version**: 4.0.0.1-beta04-1347  with .NET 5.0.01

**Platform(s)**: Does the problem occur on Windows, Android...?
For now I am only testing it on windows. 

**Describe the bug**
Cant add more items to dictionary in inspector, it stops after 1 item as added, then it doesnt let u add more when clicking
the green "+" sign. 

**To Reproduce**
1. Open existing .cs scriptt (i. e CharachterScript)
2. add a dictionary of any key,value type to it
3. save solution
4. go to Inspector and press "+" on the dictionary in the inspector
5. you should see that it doesnt add more than 1 Item

**Expected behavior**
It shall add as many items to the dict as I need/want

**Screenshots**
- not needed.

**Log and callstacks**
Log is successful:
  _[(0,0)]: Info: SpaceEscape.Game -> C:\Users\shho3\OneDrive\Dokumente\Stride 
  Projects\SpaceEscape\SpaceEscape.Game\bin\Debug\netstandard2.0\SpaceEscape.Game.dll
  [(0,0)]: Info: Assembly [CustomAsset, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] has already been processed, skip it.
  [(0,0)]: Info: CustomAsset -> C:\Users\shho3\OneDrive\Desktop\StrideCustomAsset- 
 master\CustomAsset\bin\Debug\net472\CustomAsset.dll
 Info: Unloading assembly CustomAsset, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 Info: Unloading assembly SpaceEscape.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 Info: Loading assembly SpaceEscape.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 Info: Loading assembly CustomAsset, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 Info: Updating components with newly loaded assemblies_

**Additional context**
**EDIT:**
  Pls make the visual representation of a dictionary better in the inspector like show to seperate fields closely together but divided by a "|" or the like to better represent the Key-Value nature of it. Because as it is now, it looks like you can only write 1 value into the dict-field which is irrittating..

**Comment by manio143** [comment]
Currently the editor only supports dictionaries with keys of type `string` or enum. For any other type clicking **+** will create a single item of key value `default`.

**Comment by Shpendicus** [comment]
> Currently the editor only supports dictionaries with keys of type `string` or enum. For any other type clicking **+** will create a single item of key value `default`.

well then its time to expand this ;) but for real, if u can serialize any other custom type (like person) why not being able tgo fully serialize a collection of it?

**Comment by Eideren** [comment]
We're not against it, you can go ahead and make a pr to fix this

**Comment by Shpendicus** [comment]
@Eideren How to make a PR for this? and where

**Comment by manio143** [comment]
You can read through my PR which added enum support #839. You might have to get acquainted with the codebase a bit. Some issues I see in providing a general solution are:
- the type needs to override `Equals` and `GetHashCode`, otherwise it's reference is used for determining the dictionary key and that isn't preserved across processes - how do we check that?
- if the type has a custom property editor (like `Vector3`) this custom editor needs to be used - would it appear in a popup after pressing **+** or would pressing **+** add a new default entry to then be modified?
- as mentioned in your other issue (#960) can YAML serialization handle structured dictionary keys?

Ideally, when a type is not serializable we should grey out the plus and give it a tooltip that says so.

**Comment by Shpendicus** [comment]
@manio143 Sry mate i am kinda new to this PR stuff in Github, how does it work, so you want me to fix the bug in the engine? I can try tho, but guid me how to use ur Template, can I add download it directly into Stride?

**Comment by manio143** [comment]
The Stride engine is mostly developed by the community - if it's missing some functionality that you need you can try to implement it. In order to do that you need to fork the repository, build the engine locally (see my [instructional video](https://www.youtube.com/watch?v=bXSC9o-EaR8)), then modify the editor code so that it does what you want. Then you would push the changes to your fork and submit a Pull Request so that those modifications can become part of the official Stride.

The most lengthy part is reading the source code of the engine to figure out what to do and how to achieve the desired result. It took me a while to figure out on my own how to modify the editor to allow the enum keys in dictionaries. Since what you want to achieve is in the same region, you have it easier.
The main reason why things like this aren't implemented is because contributing to Stride is often part of a hobby and there's only one person working on the engine full time, mostly busy with keeping things running. So things only get implemented when someone needs them and wants to put in the time to get them working.

For this particular change, you would need to create a new subclass `DictionaryTemplateProvider` and write XAML for that template which would properly address the second point above - behavior of the **+** sign. In the template provider you would check that the key is serializable and properly hashable (first point above).
Right now the editor crashes in a horrible manner (possibly it fell into some infinite loop) if I try to use a custom serializable struct as a dictionary key, so this needs to be debugged - likely it was not desinged to handle such cases in the first place which means a lot more investigative work has to be put in (I'm including the file which did it for me: [DictTestComponent.zip](https://github.com/stride3d/stride/files/5691069/DictTestComponent.zip)) - especially regarding the point three above.

If you want to try tackling it, give it a try. You can hit me up on Stride's Discord for a longer discussion. If not, you can try approaching your problem a little differently, so that you don't need dictionaries with keys of custom classes.

**Comment by Shpendicus** [comment]
Ok thanks for this comment, yea ok, PR => Pull Request :D forgot the shortteerm haha, it would be indeed my first really meaningful commit(s). 

The sad part tho is, I would have the need to learn WPF at firstHand with XAML :/ this demotivated me abit, since i cannot start coding the mainstuff directly. But maybe I could speed up abit the learning of it and then communicate with you together to handle the stuff for the inspector

One other thing tho mate, which popped into my mind is, why you guys dont use JSON serialization for the entire Inspector, u have an incredible tool (NewtonSoft.JSON) for high performance serialization and JSON can handly AFAIKK any datatype and collection of it, and thus Stride is using fully C' internally this wouldnt be any issue to replace YAML with it, since as u reminded me, YAML has some flaws with collection types i think. So why not fully setting it up for JSON? I think this could ease alot of the process we need to handle when doing InspectorStuff.

> Since what you want to achieve is in the same region, you have it easier.
Thx alot for that^^ and for the .zip Will look into it.

**Comment by manio143** [comment]
JSON also has limitations wrt. dictionaries - only strings can be object keys. Since we already have a well functioning YAML serializer (which is notabene way more readable than JSON) with typed references support, there isn't a reason to change it.

This actually made me think of a solution - the dictionary can be serialized into a `List<KeyValuePair<K,V>>` for complex keys. I'm planning a long serialization investigation for my vacation, so it may be possible to do.

**Comment by Shpendicus** [comment]
Im currently looking into the Editor and asking myself where Can I find about the Inspector-code, as you mentioned u did find a way to implement this Enumtype as a key for the dicts can utell me where is the class for the inspector stuff? I cant find it..

**Comment by Shpendicus** [comment]
Would be nice to know since im currently really intersssted to also try to implement it, or atleast do my best in that regard

**Comment by Shpendicus** [comment]
OK i saw the "DictionaryTemplateProvider" class but it has neither XAML code nor does it implement GetHashcode/Equals, the class u mentioned above only represents "MatchNode(..)"

**Comment by Eideren** [comment]
This would be fixed by #1111 AFAIK ?
